export const AUTH_ACCEPT = 'AUTH_ACCEPT';
export const AUTH_DENIAL = 'AUTH_DENIAL';
export const AUTH_REVOKE = 'AUTH_REVOKE';
export const AUTH_ERROR  = 'AUTH_ERROR';
export const AUTH_IS_FETCHING = 'AUTH_IS_FETCHING';
export const AUTH_IS_NOT_FETCHING = 'AUTH_IS_NOT_FETCHING';

export const SR_SUBSCRIBED_REPLACE_ALL = 'SR_SUBSCRIBED_REPLACE_ALL';
export const SR_SUBSCRIBED_ADD = 'SR_SUBSCRIBED_ADD';
export const SR_SUBSCRIBED_REM = 'SR_SUBSCRIBED_REM';
export const SR_TO_SHOW = 'SR_TO_SHOW';
export const SR_NAME_TO_SHOW = 'SR_NAME_TO_SHOW';
export const SR_IS_FETCHING = 'SR_IS_FETCHING';
export const SR_IS_NOT_FETCHING = 'SR_IS_NOT_FETCHING';

export const MSG_SUCCESS = 'MSG_SUCCESS';
export const MSG_INFO = 'MSG_INFO';
export const MSG_WARNING = 'MSG_WARNING';
export const MSG_ERROR = 'MSG_ERROR';
