export const AUTH_HAS_TOKEN = 'AUTH_HAS_TOKEN';
export const AUTH_HAS_NO_TOKEN = 'AUTH_HAS_NO_TOKEN';
export const AUTH_ACCEPT = 'AUTH_ACCEPT';
export const AUTH_DENIAL = 'AUTH_DENIAL';
export const AUTH_ERROR  = 'AUTH_ERROR';
export const AUTH_IS_FETCHING = 'AUTH_IS_FETCHING';
export const AUTH_IS_NOT_FETCHING = 'AUTH_IS_NOT_FETCHING';
export const AUTH_IS_REVOKING = 'AUTH_IS_REVOKING';
export const AUTH_IS_NOT_REVOKING = 'AUTH_IS_NOT_REVOKING';

export const USER_IS_PREFETCHING = 'USER_IS_PREFETCHING';
export const USER_IS_NOT_PREFETCHING = 'USER_IS_NOT_PREFETCHING';

export const SUBSCRIPTIONS_REPLACE_ALL = 'SUBSCRIPTIONS_REPLACE_ALL';
export const SUBSCRIPTIONS_ADD = 'SUBSCRIPTIONS_ADD';
export const SUBSCRIPTIONS_REM = 'SUBSCRIPTIONS_REM';
export const LISTS_POPULAR_SUBREDDITS = 'LISTS_POPULAR_SUBREDDITS';
export const LISTS_FEED_QUEUE = 'LISTS_FEED_QUEUE';
export const LISTS_FEED_QUEUE_ADD = 'LISTS_FEED_QUEUE_ADD';
export const LISTS_FEED_QUEUE_REM = 'LISTS_FEED_QUEUE_REM';

export const SR_RECEIVE = 'SR_RECEIVE';
export const SR_COLLECTION_TO_SHOW = 'SR_COLLECTION_TO_SHOW';
export const SR_NAME_TO_SHOW = 'SR_NAME_TO_SHOW';
export const SR_IS_FETCHING = 'SR_IS_FETCHING';
export const SR_IS_NOT_FETCHING = 'SR_IS_NOT_FETCHING';

export const MSG_SUCCESS = 'MSG_SUCCESS';
export const MSG_INFO = 'MSG_INFO';
export const MSG_WARNING = 'MSG_WARNING';
export const MSG_ERROR = 'MSG_ERROR';

export const POSTS_FETCHING = 'POSTS_FETCHING';
export const POSTS_SUCCESS = 'POSTS_SUCCESS';
export const POSTS_ERROR = 'POSTS_ERROR';
export const POSTS_FORCE_REFRESH = 'POSTS_FORCE_REFRESH';
export const POSTS_SOURCE = 'POSTS_SOURCE';
export const POSTS_MULTIPLE_MODE_ON = 'POSTS_MULTIPLE_MODE_ON';
export const POSTS_MULTIPLE_MODE_OFF = 'POSTS_MULTIPLE_MODE_OFF';
